// Date: 6/11/2015 5:14:27 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package org.blockartistry.mod.ThermalRecycling.machines.entity.renderers;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class VendingModel extends ModelBase {
	// fields
	ModelRenderer Back;
	ModelRenderer Left;
	ModelRenderer Right;
	ModelRenderer Top;
	ModelRenderer Bottom;

	public VendingModel() {
		textureWidth = 128;
		textureHeight = 64;

		Back = new ModelRenderer(this, 0, 0);
		Back.addBox(0F, 0F, 0F, 16, 31, 1);
		Back.setRotationPoint(8F, -7F, 8F);
		Back.setTextureSize(128, 64);
		Back.mirror = true;
		setRotation(Back, 0F, 3.141593F, 0F);
		Left = new ModelRenderer(this, 0, 0);
		Left.addBox(0F, 0F, 0F, 16, 31, 1);
		Left.setRotationPoint(-8F, -7F, 8F);
		Left.setTextureSize(128, 64);
		Left.mirror = true;
		setRotation(Left, 0F, 1.570796F, 0F);
		Right = new ModelRenderer(this, 0, 0);
		Right.addBox(0F, 0F, 0F, 16, 31, 1);
		Right.setRotationPoint(8F, -7F, -8F);
		Right.setTextureSize(128, 64);
		Right.mirror = true;
		setRotation(Right, 0F, -1.570796F, 0F);
		Top = new ModelRenderer(this, 0, 32);
		Top.addBox(0F, 0F, 0F, 16, 1, 16);
		Top.setRotationPoint(-8F, -8F, -8F);
		Top.setTextureSize(128, 64);
		Top.mirror = true;
		setRotation(Top, 0F, 0F, 0F);
		Bottom = new ModelRenderer(this, 0, 32);
		Bottom.addBox(0F, 0F, -8F, 16, 1, 16);
		Bottom.setRotationPoint(8F, 24F, 0F);
		Bottom.setTextureSize(128, 64);
		Bottom.mirror = true;
		setRotation(Bottom, 0F, 0F, 3.141593F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Back.render(f5);
		Left.render(f5);
		Right.render(f5);
		Top.render(f5);
		Bottom.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
